name: Deploy Node.js app on Heroku

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test

    - name: Connect and deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.9.9 
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "mohole-api"
        heroku_email: ${{secrets.HEROKU_EMAIL}}